### ISSUE TITLE
Написать авторство работ.

### ISSUE THREAD

**Issue by eXisK** [qwerty123md/parallel-programming#2]
qwerty123md мне ни о чём не говорит. Напишите в readme ФИО или хотя бы свой номер из таблички https://docs.google.com/spreadsheets/d/1x9nLCPSrnpPEVpuHpTH9aUUTriZA-Hhnd4RpZdXwudA/edit#gid=0

**Comment by qwerty123md** [comment]
@eXisK Oops
Действительно, нигде не указал.

**Comment by qwerty123md** [comment]
Матеюк Илья анатольевич
